// <auto-generated />
namespace mvc2.Migrations.Transport
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class rev111 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(rev111));
        
        string IMigrationMetadata.Id
        {
            get { return "201504040838255_rev111"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
