// <auto-generated />
namespace mvc2.Migrations.Transport
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class rev13 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(rev13));
        
        string IMigrationMetadata.Id
        {
            get { return "201504091815193_rev13"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
