// <auto-generated />
namespace mvc2.Migrations.Transport
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class rev11 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(rev11));
        
        string IMigrationMetadata.Id
        {
            get { return "201504022156173_rev11"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
