using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Xml;


public class QualityData
{
    public string Type { get; set; }
    public string Vlazhnost { get; set; }
    public string Belok { get; set; }
    public string Sor { get; set; }
}


public partial class qualityXML : System.Web.UI.Page
{
    protected void Page_Load(object sender, EventArgs e)
    {

    }
    protected void Button1_Click(object sender, EventArgs e)
    {
        saveXml();
        loadXml();
    }

    protected void loadXml()
    {
        // Open a stream to the file.
        string file = Path.Combine(Request.PhysicalApplicationPath,
        @"App_Data\QualityDataList.xml");
        FileStream fs = new FileStream(file, FileMode.Open);
        XmlTextReader r = new XmlTextReader(fs);
        // Create a generic collection of products.
        List<QualityData> products = new List<QualityData>();
        // Loop through the products.
        QualityData newProduct = new QualityData();
        while (r.Read())
        {
          

                if (r.Name == "type" && r.NodeType != XmlNodeType.EndElement)
                {

                    r.Read();
                    newProduct.Type = r.Value;
                  
                  
                }
                if (r.Name == "vlazhnost" && r.NodeType != XmlNodeType.EndElement)
                {

                    r.Read();
                    newProduct.Vlazhnost = r.Value;
                  
                   
                }
                if (r.Name == "sor" && r.NodeType != XmlNodeType.EndElement)
                {

                    r.Read();
                    newProduct.Sor = r.Value;
                  

                }
                if (r.Name == "belok" && r.NodeType != XmlNodeType.EndElement)
                {

                    r.Read();
                    newProduct.Belok = r.Value;
              

                }
              
          
        }
        fs.Close();
        products.Add(newProduct);
        // Display the retrieved document.
        gridResults.DataSource = products;
        

        gridResults.DataBind();
    }

    //protected String getNodeData(String nodeNmae, XmlTextReader r)
    //{
    //    String retValue = "";
    //    if (r.Name == nodeNmae && r.NodeType != XmlNodeType.EndElement)
    //    {

    //        r.Read();
    //        retValue = r.Value;
    //      //  Response.Write(r.Value + "; ");

    //    }
        
    //    return (retValue);
    //}

    protected void saveXml()
    {
        // Place the file in the App_Data subfolder of the current website.
        // The System.IO.Path class makes it easy to build the full file name.
        string file = Path.Combine(Request.PhysicalApplicationPath,
        @"App_Data\QualityDataList.xml");
        FileStream fs = new FileStream(file, FileMode.Create);
        XmlTextWriter w = new XmlTextWriter(fs, null);
        // Set it to indent output.
        w.Formatting = Formatting.Indented;
        // Set the number of indent spaces.
        w.Indentation = 5;
        w.WriteStartDocument();
        w.WriteStartElement("QualityDataList");
        w.WriteComment("This file generated by the XmlTextWriter class.");
        // Write the first product.
        w.WriteStartElement("Product");

        w.WriteStartElement("type");
        w.WriteString("озимая");
        w.WriteEndElement();

        w.WriteStartElement("vlazhnost");
        w.WriteString("zzz");
        w.WriteEndElement();

        w.WriteStartElement("sor");
        w.WriteString("1");
        w.WriteEndElement();

        w.WriteStartElement("belok");
        w.WriteString("2");
        w.WriteEndElement();

        //end Product
        w.WriteEndElement();

        // Close the root element.
        w.WriteEndElement();
        w.WriteEndDocument();
        w.Close();
    }
    protected void TextBox1_TextChanged(object sender, EventArgs e)
    {
     
        
    }


    protected void formTheQuality()
    {
        String qs = "Сор: " + TextBox1.Text + "; Вл: " + TextBox2.Text + "; Белок: " + TextBox3.Text + "; Озимая";
        TextBox4.Text = qs;
      
    }
    protected void TextBox2_TextChanged(object sender, EventArgs e)
    {
       
        
    }
    protected void TextBox3_TextChanged(object sender, EventArgs e)
    {
       
    }
}