// <auto-generated />
namespace mvc2.Migrations.Buy
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class rev131 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(rev131));
        
        string IMigrationMetadata.Id
        {
            get { return "201503270956266_rev131"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
